pipeline {
    agent any

    stages {
       stage('Test') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                }
            }
            steps {
                sh 'mvn test'
            }
        }
         stage('Lint') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                }
            }
            steps {
                sh 'apt-get update && apt-get install -y make && rm -rf /var/lib/apt/lists/*'
                sh 'make lint'
            }
        }
         stage('Build image') {
            steps {
                script {
                    def version = readFile('VERSION').trim()
                    docker.build("devops-training-java-app:${version}", "--build-arg VERSION=${version} -f devops/Dockerfile .")
                }
            }
        }
    }
}
